### ISSUE TITLE
Monaco editor with NodeJS as backend projects

### ISSUE THREAD

**Issue by luiztessadri** [raynoppe/BLACKICEcoder#1]
Awesome project!
I found some interesting projects that uses Monaco editor with NodeJS as backend:
https://github.com/SamsungInternet/web-code I tweaked to fit my screen.
https://github.com/fmsouza/wcode.
https://github.com/coderaiser/cloudcmd this one need to set path param because default path is root. There's two ways of adjusting:
1) cloudcmd --root /data/data/com.termux/files/home.
2) editing the config.json located at /data/data/com.termux/files/usr/lib/node_modules/cloudcmd/json and change the "root":"/" to "root":"/data/data/com.termux/files/home".

**Comment by raynoppe** [comment]
Great finds. I am going to try them out. We are currently looking at moving BI from PHP to node.
