### ISSUE TITLE
Server don't work

### ISSUE THREAD

**Issue by sudo-gera** [raynoppe/BLACKICEcoder#7]
![Screenshot_20201226-225847_Termux.jpg](https://user-images.githubusercontent.com/55020604/103158365-f3422c00-47cd-11eb-997d-2d1086ed3191.jpg)

**Comment by dhirennjaypal** [comment]
same error, i guess in php update the function get_magic_quotes_gpc() is removed

**Comment by dhirennjaypal** [comment]
![Screenshot_20210227-174914](https://user-images.githubusercontent.com/30769660/109386952-2c923780-78f6-11eb-8e15-7ad2e73f8614.jpeg)
just comment these lines in lib/settings-common.php and it works
